#!/usr/bin/env bash
# install-hooks.sh — Install git pre-push validation hook
# Run once: bash scripts/install-hooks.sh

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -z "$REPO_ROOT" ]; then
  echo "❌ Not inside a git repository"
  exit 1
fi

HOOK_PATH="$REPO_ROOT/.git/hooks/pre-push"

cat > "$HOOK_PATH" << 'HOOK'
#!/usr/bin/env bash
# Pre-push hook: validate all week JSON files before pushing to remote
# Generated by scripts/install-hooks.sh

REPO_ROOT="$(git rev-parse --show-toplevel)"
VALIDATOR="$REPO_ROOT/scripts/validate-week.py"

if [ ! -f "$VALIDATOR" ]; then
  echo "⚠️  validate-week.py not found, skipping validation"
  exit 0
fi

if ! command -v python3 &>/dev/null; then
  echo "⚠️  python3 not found, skipping validation"
  exit 0
fi

echo "🔍 Running pre-push validation on week JSON files..."
python3 "$VALIDATOR" --all
STATUS=$?

if [ $STATUS -ne 0 ]; then
  echo ""
  echo "❌ Validation failed — push blocked."
  echo "   Fix errors above or run: python3 scripts/validate-week.py --all --fix"
  exit 1
fi

echo "✅ All week JSON files valid — proceeding with push."
exit 0
HOOK

chmod +x "$HOOK_PATH"
echo "✅ Pre-push hook installed at $HOOK_PATH"
echo "   It will validate backend/data/weeks/*.json before every git push."
