#!/usr/bin/env bash
# create-pr.sh
# Creates a fix branch and opens a GitHub PR if the fix agent made any changes.
# Must be run from the repo root.
#
# Env: GH_TOKEN (auto-set by GitHub Actions), FIX_SUMMARY (optional PR body suffix)

set -euo pipefail

BRANCH="fix/weekly-health-$(date -u +%Y%m%d)"
SUMMARY_FILE="agent/fix-summary.md"

# Check if there are any changes to commit
if git diff --quiet && git diff --cached --quiet; then
  echo "[create-pr] No file changes detected — skipping PR creation"
  exit 0
fi

# Abort if branch already exists on remote (duplicate run guard)
if git ls-remote --exit-code --heads origin "$BRANCH" > /dev/null 2>&1; then
  echo "[create-pr] Branch '$BRANCH' already exists on remote — skipping"
  exit 0
fi

echo "[create-pr] Creating branch: $BRANCH"
git config user.name  "pgm-health-agent[bot]"
git config user.email "pgm-health-agent[bot]@users.noreply.github.com"

git checkout -b "$BRANCH"
git add -A
git commit -m "fix: weekly health check auto-fixes $(date -u +%Y-%m-%d)

Applied by pgm-health-agent. See agent/fix-summary.md for details."

git push origin "$BRANCH"

# Build PR body from fix-summary.md
if [ -f "$SUMMARY_FILE" ]; then
  PR_BODY=$(cat "$SUMMARY_FILE")
else
  PR_BODY="${FIX_SUMMARY:-Auto-fix from weekly health check}"
fi

PR_BODY="${PR_BODY}

---
> 🤖 Auto-generated by [pgm-health-agent](../../tree/main/agent). Review each change carefully before merging."

gh pr create \
  --title "fix: weekly health check auto-fixes ($(date -u +%Y-%m-%d))" \
  --body "$PR_BODY" \
  --base main \
  --head "$BRANCH" \
  --label "health-check" 2>/dev/null || \
gh pr create \
  --title "fix: weekly health check auto-fixes ($(date -u +%Y-%m-%d))" \
  --body "$PR_BODY" \
  --base main \
  --head "$BRANCH"

echo "[create-pr] PR created on branch: $BRANCH"
